# Form implementation generated from reading ui file 'alarm_task.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 202)
        self.task_al = QtWidgets.QPushButton(Dialog)
        self.task_al.setGeometry(QtCore.QRect(140, 230, 75, 24))
        self.task_al.setObjectName("task_al")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 40, 251, 111))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.task_al.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.task_al.setText(_translate("Dialog", "verstanden"))
        self.label.setText(_translate("Dialog", "Eingabe ungülig"))
